.TH CHECKERS 1 "23 January 2026"
.SH NAME
checkers \- 3D checkers (for two players)
.SH SYNOPSIS
.B checkers
.SH DESCRIPTION
On systems with keyboard input, controls are as such:
.TP
.B Arrow keys
Move to select a piece on the board, a possible move for a given piece, or
menu item.
.TP
.B Space
Choose the selected menu item; choose a piece or move.
.TP
.B Backspace
Back out of moving a piece so you can select another.
.TP
.B Escape
Go to the main menu.
.PP
From the menu you can select options which should all be self-explanatory, such
as starting a new local game or a network game.
.SH BUGS
This is a pretty basic program so far; player vs. computer is hopefully
forthcoming; complete mouse support would be really nice too.
