#ifndef _INPUT_MAPPING_H_
#define _INPUT_MAPPING_H_
#include "input.h"

static int input_mapping[] = {
	[INPUT_UP] = PSP_CTRL_UP,
	[INPUT_DOWN] = PSP_CTRL_DOWN,
	[INPUT_LEFT] = PSP_CTRL_LEFT,
	[INPUT_RIGHT] = PSP_CTRL_RIGHT,
	[INPUT_PAUSE] = PSP_CTRL_START,
	[INPUT_ACCEPT] = PSP_CTRL_CROSS,
	[INPUT_BACK] = PSP_CTRL_CIRCLE
};

#endif /* !_INPUT_MAPPING_H_ */
