CC=	x86_64-w64-mingw32-gcc
#CC=	gcc
PROGRAM=checkers.exe
OBJECTS=checkers.o game.o game_display.o game_interaction.o game_checkers.o menu.o main-win.o sprite.o scenegraph-gl.o texture.o input.o
LDFLAGS=-lgdi32 -lopengl32 -lglu32 -mwindows
CFLAGS=	-Wall -W -I. -fcommon

$(PROGRAM): $(OBJECTS)
	$(CC) -o $@ $(OBJECTS) $(LDFLAGS)

clean:
	rm -f $(PROGRAM) $(OBJECTS)
