TARGET = checkers

OBJS = checkers.o main-psp.o main_menu.o game.o game_display.o game_interaction.o game_checkers.o sprite.o scenegraph-psp.o texture.o input.o text.o

BUILD_PRX=0
CFLAGS=-g
EXTRA_TARGETS = EBOOT.PBP

LIBS = -lpspgu -lpspgum -lstdc++ -lpspdebugkb

PSPSDK=$(shell psp-config --pspsdk-path)
include $(PSPSDK)/lib/build.mak
