TARGET = checkers

OBJS = checkers.o init-psp.o menu.o game.o scenegraph-psp.o texture.o input.o

BUILD_PRX=0
CFLAGS=-g
EXTRA_TARGETS = EBOOT.PBP

LIBS = -lpspgu -lpspgum -lstdc++ -lpspdebugkb

PSPSDK=$(shell psp-config --pspsdk-path)
include $(PSPSDK)/lib/build.mak
