CC=		i686-w64-mingw32-gcc
PROGRAM=	checkers.exe
OBJECTS=	checkers.o game.o game_display.o game_interaction.o game_checkers.o menu.o net_menu.o main-win.o sprite.o scenegraph-gl.o texture.o text.o input.o gui.o text_input.o game_net.o game_computer.o game_save.o select_file.o error.o
CFLAGS+=	-Wall -g $(CFLAGS_DNS_SD$(USE_DNS_SD))
CFLAGS_DNS_SD1=-DUSE_DNS_SD
LDFLAGS+=	-mwindows
LDFLAGS+=	-lgdi32 -lopengl32 -lwinmm -lws2_32 \
		$(LIBS_DNS_SD$(USE_DNS_SD))
LIBS_DNS_SD1=	-ldnssd

$(PROGRAM): $(OBJECTS)
	$(CC) -o $@ $(OBJECTS) $(LDFLAGS)

clean:
	rm -f $(PROGRAM) $(OBJECTS)
