PROGRAM=Checkers
OBJECTS=checkers.o game.o game_display.o game_interaction.o game_checkers.o menu.o net_menu.o main-osx.o sprite.o scenegraph-gl.o shadow.o texture.o input.o text.o gui.o text_input.o game_net.o game_computer.o game_save.o model.o asset.o error.o select_file-osx.o CheckersView.o ApplicationDelegate.o
LDFLAGS=-framework Cocoa -framework OpenGL
CFLAGS=	-Wall -O2 -std=gnu99 $(CFLAGS_DNS_SD$(USE_DNS_SD))
CFLAGS_DNS_SD=	-DUSE_DNS_SD

Checkers.app: $(PROGRAM)
	mkdir -p $@/Contents/MacOS
	mkdir -p $@/Contents/Resources
	cp cocoa/Info.plist $@/Contents
	cp -r cocoa/English.lproj assets/textures assets/models $@/Contents/Resources
	cp $< $@/Contents/MacOS

$(PROGRAM): $(OBJECTS)
	$(CC) -o $@ $(OBJECTS) $(LDFLAGS)

clean:
	rm -f $(PROGRAM) $(OBJECTS)
